name: localenviroment CI

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths:
      - 'config.yaml'
      - '.github/workflows/localenviroment-ci.yml'
      - 'localenviroment'
      - 'env/*'

# Abort the previous running CI workflow in the same pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Verify local env execution - python
        run: |
          ./localenviroment python env/python/demo.py

      - name: Verify local env execution - powershell
        run: |
          ./localenviroment powershell env/powershell/demo.ps1

      - name: Verify local env execution - groovy
        run: |
          ./localenviroment groovy env/groovy/demo.groovy

      - name: Verify local env execution - javascript
        run: |
          ./localenviroment javascript env/javascript/demo.js

      - name: Verify local env execution - golang
        run: |
          ./localenviroment golang env/golang/demo.go

      - name: Verify local env execution - java
        run: |
          ./localenviroment java env/java/demo.java
